import { beforeEach, describe, expect, it, vi } from "vitest";

/**
 * THE HUMAN GATE (spec §4).
 *
 * "Nothing generated by the model reaches a client without a paralegal approval
 * recorded in the audit log." These tests hold the three doors shut:
 *
 *   sendApproved     refuses without a paralegal id, and writes the audit entry
 *                    BEFORE the provider is called, so an approval is never lost to a
 *                    delivery failure
 *   sendTemplate     only clinic-owned fixed text, attributed as template:<name>
 *   sendGroundedAuto refuses unless the clinic opted in AND a citation is present
 */

const sent: { to: string; body: string; kind: "sms" | "email" }[] = [];
const audits: { action: string; actor: string; payload: Record<string, unknown> }[] = [];
const inserted: Record<string, unknown>[] = [];

const CLIENT = { id: "client-1", phone: "+15551230001", email: null, preferredLanguage: "es" };
const CASE = { id: "case-1", clientId: "client-1", status: "awaiting_review", caseType: "I-485" };

let failDelivery = false;

vi.mock("@/db/client", () => {
  const db = {
    query: {
      cases: { findFirst: async () => ({ ...CASE, client: CLIENT }) },
      escalations: { findFirst: async () => undefined },
    },
    insert: () => ({
      values: (v: Record<string, unknown>) => {
        inserted.push(v);
        return { returning: async () => [{ id: `msg-${inserted.length}` }] };
      },
    }),
    update: () => ({ set: () => ({ where: async () => undefined, returning: async () => [] }) }),
  };
  return { getDb: async () => db, schema: { messages: {}, cases: {}, escalations: {}, auditEntries: {} } };
});

vi.mock("@/lib/audit", () => ({
  AGENT_ACTOR: "agent",
  writeAudit: async (entry: { action: string; actor: string; payload?: Record<string, unknown> }) => {
    audits.push({ action: entry.action, actor: entry.actor, payload: entry.payload ?? {} });
  },
}));

vi.mock("@/lib/channel", () => ({
  getChannelProvider: async () => ({
    name: "mock",
    identity: () => ({ phone: "+15550000000", email: "docs@clinic.local" }),
    sendSms: async (to: string, body: string) => {
      if (failDelivery) throw new Error("carrier rejected the message");
      sent.push({ to, body, kind: "sms" });
      return { externalId: "ext-1" };
    },
    sendEmail: async (to: string, _s: string, body: string) => {
      sent.push({ to, body, kind: "email" });
      return { externalId: "ext-2" };
    },
  }),
}));

// No model: translateText returns the English unchanged, which is the honest fallback.
vi.mock("@/lib/llm/client", () => ({ completeText: async () => null, isLlmConfigured: () => false }));

const { sendApproved, sendTemplate, sendGroundedAuto, isAutoSendEnabled } = await import("./reply");

beforeEach(() => {
  sent.length = 0;
  audits.length = 0;
  inserted.length = 0;
  failDelivery = false;
  delete process.env.AUTO_SEND_GROUNDED_ANSWERS;
});

describe("sendApproved", () => {
  it("refuses without a paralegal id", async () => {
    await expect(
      sendApproved({ caseId: "case-1", paralegalId: "", englishText: "The date of birth does not match." }),
    ).rejects.toThrow(/paralegal id/i);
    expect(sent).toHaveLength(0);
  });

  it("refuses to send empty text", async () => {
    await expect(sendApproved({ caseId: "case-1", paralegalId: "auth0|p1", englishText: "   " })).rejects.toThrow();
    expect(sent).toHaveLength(0);
  });

  it("records the approving paralegal on the message and in the audit log", async () => {
    await sendApproved({ caseId: "case-1", paralegalId: "auth0|p1", englishText: "Please send a clearer copy." });
    expect(inserted[0]).toMatchObject({ direction: "outbound", approvedBy: "auth0|p1" });
    const entry = audits.find((a) => a.action === "message.sent");
    expect(entry?.actor).toBe("auth0|p1");
    expect(entry?.payload).toMatchObject({ paralegalId: "auth0|p1", englishText: "Please send a clearer copy." });
    expect(sent).toHaveLength(1);
  });

  it("keeps the approval record when delivery fails", async () => {
    failDelivery = true;
    await expect(sendApproved({ caseId: "case-1", paralegalId: "auth0|p1", englishText: "Anything" })).rejects.toThrow();
    // The approval happened; only the carrier failed. Losing that record would mean a
    // paralegal's decision vanished.
    expect(audits.some((a) => a.action === "message.sent" && a.actor === "auth0|p1")).toBe(true);
    expect(audits.some((a) => a.action === "message.blocked")).toBe(true);
  });
});

describe("sendTemplate", () => {
  it("attributes clinic text to the template, never to a person", async () => {
    await sendTemplate({ caseId: "case-1", template: "document.received", vars: { docName: "Pasaporte" } });
    expect(inserted[0]).toMatchObject({ approvedBy: "template:document.received" });
    expect(audits.find((a) => a.action === "message.sent")?.actor).toBe("agent");
  });

  it("sends the human translation and audits the English it came from", async () => {
    await sendTemplate({ caseId: "case-1", template: "document.received", vars: { docName: "Pasaporte" } });
    expect(sent[0].body).toBe("Recibimos: Pasaporte. ¡Gracias!");
    expect(audits.find((a) => a.action === "message.sent")?.payload).toMatchObject({
      source: "language_pack",
      englishText: "Received: Pasaporte. Thank you!",
    });
  });
});

describe("sendGroundedAuto", () => {
  const citation = { title: "USCIS", url: "https://www.uscis.gov/i-485", quote: "a".repeat(60), retrievedAt: new Date().toISOString() };

  it("is off unless the clinic turns it on", async () => {
    expect(isAutoSendEnabled()).toBe(false);
    await expect(sendGroundedAuto({ caseId: "case-1", text: "An explanation.", citation })).rejects.toThrow(
      /AUTO_SEND_GROUNDED_ANSWERS/,
    );
  });

  it("refuses without a citation even when it is on", async () => {
    process.env.AUTO_SEND_GROUNDED_ANSWERS = "true";
    await expect(
      // @ts-expect-error deliberately omitting the citation the signature requires
      sendGroundedAuto({ caseId: "case-1", text: "An explanation." }),
    ).rejects.toThrow(/citation/);
    expect(sent).toHaveLength(0);
  });

  it("blocks advice language and records the block", async () => {
    process.env.AUTO_SEND_GROUNDED_ANSWERS = "true";
    await expect(
      sendGroundedAuto({ caseId: "case-1", text: "You are eligible to apply.", citation }),
    ).rejects.toThrow(/blocked/);
    expect(sent).toHaveLength(0);
    expect(audits.some((a) => a.action === "message.blocked")).toBe(true);
  });
});
